[server]
  host = "127.0.0.1"
  port = 3010
  kind = "lazy"

  # Checkpointing state.
  checkpointing = true

  # Checkpoint interval in number of blocks.
  checkpointInterval = 2000

  # Enable state creation
  enableState = true

  # Boolean to filter logs by contract.
  filterLogs = true

  # Max block range for which to return events in eventsInRange GQL query.
  # Use -1 for skipping check on block range.
  maxEventsBlockRange = -1

  # Flag to specify whether RPC endpoint supports block hash as block tag parameter
  rpcSupportsBlockHashParam = false

  [server.p2p]
    enableRelay = true
    enablePeer = false

    [server.p2p.relay]
      host = "127.0.0.1"
      port = 9090
      relayPeers = []
      denyMultiaddrs = []
      peerIdFile = ''
      announce = ''
      pubsub = ''
      enableDebugInfo = true

    [server.p2p.peer]
      relayMultiaddr = ''
      denyMultiaddrs = []
      pubSubTopic = 'mobymask'
      peerIdFile = ''
      pubsub = ''
      enableDebugInfo = true
      enableL2Txs = false
      pingInterval = 4000
      pingTimeout = 1500

      [server.p2p.peer.l2TxsConfig]
        privateKey = ''
        contractAddress = ''

    [server.p2p.nitro]
      store = ''
      privateKey = ''
      chainPrivateKey = ''

      [server.p2p.nitro.payments]
        ratesFile = ''
        requestTimeoutInSecs = 10

        [server.p2p.nitro.payments.cache]
          maxAccounts = 1000
          accountTTLInSecs = 1800
          maxVouchersPerAccount = 1000
          voucherTTLInSecs = 300
          maxPaymentChannels = 10000
          paymentChannelTTLInSecs = 1800

    [server.p2p.consensus]
      enabled = true
      publicKey = ''
      privateKey = ''
      watcherPartyFile = ''

[metrics]
  host = "127.0.0.1"
  port = 9000

  [metrics.gql]
    port = 9001

[database]
  type = "postgres"
  host = "localhost"
  port = 5432
  database = "mobymask-v2-watcher"
  username = "postgres"
  password = "postgres"
  synchronize = true
  logging = false

[upstream]
  [upstream.ethServer]
    gqlApiEndpoint = "http://127.0.0.1:8082/graphql"
    rpcProviderEndpoint = "http://127.0.0.1:8081"
    rpcProviderMutationEndpoint = "http://127.0.0.1:8545"

    [upstream.ethServer.rpcProviderNitroNode]
      address = ""
      multiAddr = ""
      amount = "5000"

  [upstream.cache]
    name = "requests"
    enabled = false
    deleteOnStart = false

[jobQueue]
  dbConnectionString = "postgres://postgres:postgres@localhost/mobymask-v2-watcher-job-queue"
  maxCompletionLagInSecs = 300
  jobDelayInMilliSecs = 100
  eventsInBatch = 50
  blockDelayInMilliSecs = 2000
  prefetchBlocksInMem = true
  prefetchBlockCount = 10
