freeGqlQueriesLimit = ''

freeGqlQueries = ['latestBlock']

[gqlQueries]
  multiNonce = ''
  _owner = ''
  isRevoked = ''
  isPhisher = ''
  isMember = ''

[chainTrasactions]
  invoke = ''
  revoke = ''
